import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.scss'
import {Drawer} from "@/app/UI/Drawer/Drawer";
import {ReactNode} from "react";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Шифрование',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="ru" data-lt-installed={true} >
        <body className={inter.className}>
        <Drawer>
            <div className='container mx-auto p-4'>
                {children}
            </div>
        </Drawer>
        </body>
        </html>
    )
}
